### ISSUE TITLE
Visual: Things with a plus in front of them look distinct from things without a plus/minus.

### ISSUE THREAD

**Issue by Lomilar** [cassproject/cass-editor#186]

**Comment by siuc-nate** [comment]
Potentially related to this, something I encountered today:

The lack of spacing on the left for things without a plus/minus icon results in an implied hierarchy that isn't actually there:
![image](https://user-images.githubusercontent.com/21346519/38211708-fca4a16c-3680-11e8-8e74-f9173fa6cd5b.png)
should actually look like
![image](https://user-images.githubusercontent.com/21346519/38211722-07eb2c1c-3681-11e8-998e-5e15c9ad6e71.png)

I have been experimenting with spacing fixes on the CSS on my end, but this may be something better resolved within CASS's own CSS.  For reference, the above image uses this bit of CSS to achieve the desired alignment:
```
.collapse .fa { margin: 0 2px 0 0; }
.competency:not(.expandable) { padding-left: 25px; }
```
There is probably a better solution (or some other icon that could be used for non-expanding elements?), but this works for me for now.  Let me know if/when a fix for this is in place so I can remove the CSS on my end that will probably interfere with it.

**Comment by Lomilar** [comment]
Had to include a change for jitter-hover, but yeah, basically the same thing. Not sure about the `.collapse .fa`, but kept it there since you did as well.

```css

.collapse .fa { 
    margin: 0 2px 0 0; 
} 
 
.competency:not(.expandable) { 
    padding-left: calc(34px + 2px + 2px); 
} 
 
.competency:not(.expandable):hover { 
-
    padding-left: calc(34px + 2px); 
} 
```
